version: '3'
services:
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - server
    environment:
      - DOMAIN=web
      - PORT=80
      - AUTH_TOKEN=<YOUR NGROK AUTH_TOKEN>
      
  server:
    build: .
    container_name: pymessenger
